### ISSUE TITLE
Why does it have the overlay with Proceed to Payment button?

### ISSUE THREAD

**Issue by etalented** [etalented/multipay#36]

**Comment by etalented** [comment]
Fixed by @david-szabo97
This was a WorldPay specific issue. I fixed it.

**Comment by etalented** [comment]
Issue still occurs.
With valid amount & reference, using WorldPay as payment, Proceed to Payment overlay shows over the top of payment overlay- see attached
![screen shot 2018-11-25 at 11 56 36](https://user-images.githubusercontent.com/20968408/48978273-6043de80-f0a9-11e8-9a16-fe3d96ba6d42.png)

**Comment by etalented** [comment]
@david-szabo97 also please confirm- is this overlay needed? I would prefer not to have it

**Comment by etalented** [comment]
@david-szabo97 can we do the same solution for all payment methods?

**Comment by david-szabo97** [comment]
https://github.com/etalented/multipay/commit/3e8a32f91dde362f55e38fc364c0adba3fd19362
